import type {
  ApartmentStatus,
  City,
  Currency,
  LeadStatus,
  Messenger,
  RentalPeriod,
  UtilitiesPayment,
} from '../../src/generated/prisma/enums';

import type { SceneKind } from './illustrations';

/**
 * Демонстрационные объекты. Все помечаются isDemo = true и значком «Демо» на сайте,
 * чтобы их нельзя было выдать за реальные предложения. Удаляются одной кнопкой в админке.
 */
export interface DemoApartment {
  key: string;
  title: string;
  city: City;
  district: string;
  address: string;
  price: number;
  currency: Currency;
  rooms: number;
  area: number;
  floor: number;
  totalFloors: number;
  description: string;
  furnished: boolean;
  hasAppliances: boolean;
  childrenAllowed: boolean;
  petsAllowed: boolean;
  dogsAllowed: boolean;
  catsAllowed: boolean;
  rentalPeriod: RentalPeriod;
  deposit: number | null;
  utilities: UtilitiesPayment;
  utilitiesNote: string | null;
  status: ApartmentStatus;
  /** Сколько дней назад опубликовано */
  publishedDaysAgo: number;
  palette: number;
  scenes: SceneKind[];
}

export const DEMO_APARTMENTS: DemoApartment[] = [
  {
    key: 'kyiv-obolon-1',
    title: 'Уютная 1-комнатная квартира у метро «Минская»',
    city: 'KYIV',
    district: 'obolonskyi',
    address: 'Оболонский проспект, 5 минут пешком до метро',
    price: 14_000,
    currency: 'UAH',
    rooms: 1,
    area: 38,
    floor: 9,
    totalFloors: 16,
    description:
      'Светлая квартира с современным ремонтом в тихом дворе. Отдельная кухня, совмещённый санузел, застеклённый балкон с видом на зелёный двор.\n\nВ квартире есть всё для комфортной жизни: двуспальная кровать, шкаф-купе, холодильник, стиральная машина и посудомойка. Рядом парк, набережная Днепра, супермаркеты и спортзал.',
    furnished: true,
    hasAppliances: true,
    childrenAllowed: true,
    petsAllowed: true,
    dogsAllowed: false,
    catsAllowed: true,
    rentalPeriod: 'MONTHS_6',
    deposit: 14_000,
    utilities: 'SEPARATE',
    utilitiesNote: 'по счётчикам, около 2 000 ₴ в месяц',
    status: 'PUBLISHED',
    publishedDaysAgo: 2,
    palette: 2,
    scenes: ['living', 'bedroom', 'kitchen', 'bathroom'],
  },
  {
    key: 'kyiv-pechersk-2',
    title: 'Светлая 2-комнатная квартира на Печерске рядом с парком',
    city: 'KYIV',
    district: 'pecherskyi',
    address: 'бульвар Леси Украинки',
    price: 32_000,
    currency: 'UAH',
    rooms: 2,
    area: 68,
    floor: 7,
    totalFloors: 12,
    description:
      'Просторная квартира с раздельными комнатами и большой кухней-гостиной. Высокие потолки, панорамные окна, качественная мебель и вся необходимая техника.\n\nДом с охраняемой территорией и подземным паркингом. В пешей доступности — парки, кафе, школы и детские сады. Отлично подойдёт семье с ребёнком; можно с небольшой собакой.',
    furnished: true,
    hasAppliances: true,
    childrenAllowed: true,
    petsAllowed: true,
    dogsAllowed: true,
    catsAllowed: false,
    rentalPeriod: 'MONTHS_12',
    deposit: 32_000,
    utilities: 'SEPARATE',
    utilitiesNote: null,
    status: 'PUBLISHED',
    publishedDaysAgo: 4,
    palette: 0,
    scenes: ['living', 'view', 'bedroom', 'kitchen', 'bathroom'],
  },
  {
    key: 'kyiv-shevchenko-3',
    title: 'Просторная 3-комнатная квартира в историческом центре',
    city: 'KYIV',
    district: 'shevchenkivskyi',
    address: 'улица Ярославов Вал',
    price: 1_300,
    currency: 'USD',
    rooms: 3,
    area: 95,
    floor: 4,
    totalFloors: 6,
    description:
      'Квартира в доме начала XX века после бережной реконструкции: сохранены лепнина и высокие потолки, при этом новые коммуникации и тёплые полы в санузлах.\n\nТри изолированные комнаты, кабинет с рабочим местом, кухня-столовая. До исторических улиц и метро — несколько минут пешком.',
    furnished: true,
    hasAppliances: true,
    childrenAllowed: true,
    petsAllowed: false,
    dogsAllowed: false,
    catsAllowed: false,
    rentalPeriod: 'MONTHS_12',
    deposit: 1_300,
    utilities: 'SEPARATE',
    utilitiesNote: 'по счётчикам',
    status: 'PUBLISHED',
    publishedDaysAgo: 9,
    palette: 4,
    scenes: ['living', 'workspace', 'bedroom', 'kitchen', 'bathroom'],
  },
  {
    key: 'kyiv-darnytsia-2',
    title: '2-комнатная квартира в новом доме на левом берегу',
    city: 'KYIV',
    district: 'darnytskyi',
    address: 'проспект Бажана',
    price: 19_500,
    currency: 'UAH',
    rooms: 2,
    area: 62,
    floor: 14,
    totalFloors: 25,
    description:
      'Квартира в новом жилом комплексе с закрытым двором и детскими площадками. Свежий ремонт, встроенная кухня, гардеробная.\n\nМожно с детьми и с животными — рядом большой парк для прогулок. Метро и крупный торговый центр в нескольких минутах.',
    furnished: true,
    hasAppliances: true,
    childrenAllowed: true,
    petsAllowed: true,
    dogsAllowed: true,
    catsAllowed: true,
    rentalPeriod: 'MONTHS_6',
    deposit: 0,
    utilities: 'SEPARATE',
    utilitiesNote: null,
    status: 'PUBLISHED',
    publishedDaysAgo: 12,
    palette: 5,
    scenes: ['view', 'living', 'bedroom', 'kitchen'],
  },
  {
    key: 'kyiv-golosiiv-1',
    title: 'Компактная 1-комнатная квартира с ремонтом',
    city: 'KYIV',
    district: 'golosiivskyi',
    address: 'улица Васильковская',
    price: 12_500,
    currency: 'UAH',
    rooms: 1,
    area: 32,
    floor: 3,
    totalFloors: 9,
    description:
      'Уютная квартира для одного человека или пары. Кухня-гостиная, спальная зона, новая сантехника.\n\nКоммунальные платежи включены в стоимость. Рядом метро, остановки общественного транспорта и продуктовые магазины.',
    furnished: true,
    hasAppliances: true,
    childrenAllowed: false,
    petsAllowed: false,
    dogsAllowed: false,
    catsAllowed: false,
    rentalPeriod: 'MONTHS_3',
    deposit: null,
    utilities: 'INCLUDED',
    utilitiesNote: null,
    status: 'PUBLISHED',
    publishedDaysAgo: 20,
    palette: 3,
    scenes: ['living', 'kitchen', 'bathroom'],
  },
  {
    key: 'kyiv-podil-2',
    title: '2-комнатная квартира на Подоле',
    city: 'KYIV',
    district: 'podilskyi',
    address: 'улица Ярославская',
    price: 24_000,
    currency: 'UAH',
    rooms: 2,
    area: 55,
    floor: 2,
    totalFloors: 5,
    description:
      'Квартира в малоэтажном доме в атмосферном районе. Две комнаты, кухня, балкон. Рядом кофейни, набережная и метро.',
    furnished: true,
    hasAppliances: true,
    childrenAllowed: true,
    petsAllowed: false,
    dogsAllowed: false,
    catsAllowed: false,
    rentalPeriod: 'MONTHS_6',
    deposit: 24_000,
    utilities: 'SEPARATE',
    utilitiesNote: null,
    status: 'RENTED',
    publishedDaysAgo: 40,
    palette: 1,
    scenes: ['living', 'bedroom'],
  },
  {
    key: 'dnipro-center-1',
    title: '1-комнатная квартира в центре на проспекте Яворницкого',
    city: 'DNIPRO',
    district: 'tsentralnyi',
    address: 'проспект Дмитрия Яворницкого',
    price: 10_500,
    currency: 'UAH',
    rooms: 1,
    area: 42,
    floor: 5,
    totalFloors: 9,
    description:
      'Квартира в самом центре города: рядом набережная, парки, театры и деловые центры. Современный ремонт, большая кровать, рабочее место у окна.\n\nМожно с кошкой. Отличный вариант для тех, кто работает из дома.',
    furnished: true,
    hasAppliances: true,
    childrenAllowed: true,
    petsAllowed: true,
    dogsAllowed: false,
    catsAllowed: true,
    rentalPeriod: 'MONTHS_6',
    deposit: 10_500,
    utilities: 'SEPARATE',
    utilitiesNote: null,
    status: 'PUBLISHED',
    publishedDaysAgo: 1,
    palette: 3,
    scenes: ['workspace', 'living', 'kitchen', 'bathroom'],
  },
  {
    key: 'dnipro-sobornyi-2',
    title: '2-комнатная квартира у набережной с балконом',
    city: 'DNIPRO',
    district: 'sobornyi',
    address: 'Сичеславская набережная',
    price: 16_000,
    currency: 'UAH',
    rooms: 2,
    area: 64,
    floor: 11,
    totalFloors: 16,
    description:
      'Квартира с видом на Днепр: большая гостиная, спальня, застеклённый балкон. Мебель и техника в отличном состоянии.\n\nМожно с собакой, рядом набережная для прогулок. Подходит для семьи с детьми.',
    furnished: true,
    hasAppliances: true,
    childrenAllowed: true,
    petsAllowed: true,
    dogsAllowed: true,
    catsAllowed: false,
    rentalPeriod: 'MONTHS_12',
    deposit: 16_000,
    utilities: 'SEPARATE',
    utilitiesNote: 'зимой около 3 000 ₴',
    status: 'PUBLISHED',
    publishedDaysAgo: 3,
    palette: 2,
    scenes: ['view', 'living', 'bedroom', 'kitchen', 'bathroom'],
  },
  {
    key: 'dnipro-shevchenko-3',
    title: 'Семейная 3-комнатная квартира с двумя санузлами',
    city: 'DNIPRO',
    district: 'shevchenkivskyi',
    address: 'проспект Науки',
    price: 23_000,
    currency: 'UAH',
    rooms: 3,
    area: 88,
    floor: 6,
    totalFloors: 10,
    description:
      'Просторная квартира для большой семьи: три изолированные комнаты, кухня-столовая, два санузла, кладовая.\n\nМожно с детьми и животными. Во дворе детская площадка, рядом школа, детский сад и парк.',
    furnished: true,
    hasAppliances: true,
    childrenAllowed: true,
    petsAllowed: true,
    dogsAllowed: true,
    catsAllowed: true,
    rentalPeriod: 'MONTHS_12',
    deposit: 23_000,
    utilities: 'SEPARATE',
    utilitiesNote: null,
    status: 'PUBLISHED',
    publishedDaysAgo: 15,
    palette: 0,
    scenes: ['living', 'bedroom', 'kitchen', 'bathroom', 'workspace'],
  },
  {
    key: 'dnipro-amur-1',
    title: 'Недорогая 1-комнатная квартира с мебелью',
    city: 'DNIPRO',
    district: 'amur-nyzhnodniprovskyi',
    address: 'улица Строителей',
    price: 8_500,
    currency: 'UAH',
    rooms: 1,
    area: 36,
    floor: 2,
    totalFloors: 9,
    description:
      'Аккуратная квартира с мебелью и основной техникой. Хорошая транспортная развязка, рядом рынок и супермаркеты.\n\nБез депозита, можно заехать в ближайшие дни.',
    furnished: true,
    hasAppliances: true,
    childrenAllowed: true,
    petsAllowed: false,
    dogsAllowed: false,
    catsAllowed: false,
    rentalPeriod: 'MONTHS_3',
    deposit: 0,
    utilities: 'SEPARATE',
    utilitiesNote: null,
    status: 'PUBLISHED',
    publishedDaysAgo: 25,
    palette: 4,
    scenes: ['living', 'kitchen', 'bathroom'],
  },
  {
    key: 'dnipro-novokodatskyi-2',
    title: '2-комнатная квартира рядом с парком',
    city: 'DNIPRO',
    district: 'novokodatskyi',
    address: 'улица Калиновая',
    price: 12_000,
    currency: 'UAH',
    rooms: 2,
    area: 52,
    floor: 4,
    totalFloors: 9,
    description: 'Квартира временно снята с публикации: владелец завершает косметический ремонт.',
    furnished: false,
    hasAppliances: true,
    childrenAllowed: true,
    petsAllowed: true,
    dogsAllowed: false,
    catsAllowed: true,
    rentalPeriod: 'MONTHS_6',
    deposit: 12_000,
    utilities: 'SEPARATE',
    utilitiesNote: null,
    status: 'HIDDEN',
    publishedDaysAgo: 30,
    palette: 5,
    scenes: ['living', 'bedroom'],
  },
];

export interface DemoLead {
  name: string;
  phone: string;
  messenger: Messenger | null;
  message: string | null;
  apartmentKey: string | null;
  status: LeadStatus;
  hoursAgo: number;
}

export const DEMO_LEADS: DemoLead[] = [
  {
    name: 'Анна (демо)',
    phone: '+380500000001',
    messenger: 'TELEGRAM',
    message: 'Здравствуйте! Квартира ещё свободна? Можно посмотреть в субботу днём?',
    apartmentKey: 'kyiv-pechersk-2',
    status: 'NEW',
    hoursAgo: 3,
  },
  {
    name: 'Игорь (демо)',
    phone: '+380670000002',
    messenger: 'PHONE',
    message: 'Ищу 2-комнатную в Днепре до 18 000 ₴, живу с собакой. Рассмотрю варианты у набережной.',
    apartmentKey: null,
    status: 'IN_PROGRESS',
    hoursAgo: 28,
  },
  {
    name: 'Мария (демо)',
    phone: '+380930000003',
    messenger: 'VIBER',
    message: null,
    apartmentKey: 'dnipro-center-1',
    status: 'COMPLETED',
    hoursAgo: 72,
  },
];
